name: Webhook trigger

on:
  workflow_dispatch:
    inputs:
      files_path: 
        description: "Path to RPM files"
        default: "."
        required: false
      server:
        description: "Host target yumrepo"
        default: "10.84.113.224"
        required: false
      baseurl: 
        description: "Remote path for binaries"
        default: "/tmp"
        required: false
      upload:
        description: "Wether upload or not (yes/no)"
        default: "yes"
        required: false
      update:
        description: "Update remote repository (yes/no)"
        default: "yes"
        required: false
    
jobs:
  webhook:
    runs-on: "ubuntu-20.04"

    steps:
      - name: Webhook
        run: |
         curl -XPOST -u "${{ secrets.ACTION_USER }}:${{ secrets.ACTION_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/gannettdigital/cloud-engineering-workflows/actions/workflows/Consul-rpm.yaml/dispatches --data '{"ref":"main","inputs":{"files_path":"'${{ github.event.inputs.files_path'","server":"'${{ github.event.inputs.server'","baseurl":"'${{ github.event.inputs.baseurl }}'","upload":"'${{ github.event.inputs.upload }}'","update":"'${{ github.event.inputs.update }}'"}}'
